import { ComboMove } from './ComboEngine';

export function createComboCatalog(): ComboMove[] {
  return [
    { id: 'knight-combo-1', name: 'KNIGHT Technique 1', sequence: ['light', 'heavy'], maximumGap: 420, score: 40, damageMultiplier: 1.10, resourceReward: 3, tags: ['knight', 'length-2'] },
    { id: 'knight-combo-2', name: 'KNIGHT Technique 2', sequence: ['heavy', 'dodge', 'special'], maximumGap: 445, score: 58, damageMultiplier: 1.16, resourceReward: 4, tags: ['knight', 'length-3'] },
    { id: 'knight-combo-3', name: 'KNIGHT Technique 3', sequence: ['dodge', 'special', 'light', 'heavy'], maximumGap: 470, score: 76, damageMultiplier: 1.22, resourceReward: 5, tags: ['knight', 'length-4'] },
    { id: 'knight-combo-4', name: 'KNIGHT Technique 4', sequence: ['special', 'light', 'heavy', 'dodge', 'special'], maximumGap: 495, score: 94, damageMultiplier: 1.28, resourceReward: 6, tags: ['knight', 'length-5'] },
    { id: 'knight-combo-5', name: 'KNIGHT Technique 5', sequence: ['light', 'heavy', 'dodge', 'special', 'light', 'heavy'], maximumGap: 520, score: 112, damageMultiplier: 1.34, resourceReward: 7, tags: ['knight', 'length-6'] },
    { id: 'knight-combo-6', name: 'KNIGHT Technique 6', sequence: ['heavy', 'dodge'], maximumGap: 545, score: 130, damageMultiplier: 1.40, resourceReward: 8, tags: ['knight', 'length-2'] },
    { id: 'knight-combo-7', name: 'KNIGHT Technique 7', sequence: ['dodge', 'special', 'light'], maximumGap: 570, score: 148, damageMultiplier: 1.46, resourceReward: 9, tags: ['knight', 'length-3'] },
    { id: 'knight-combo-8', name: 'KNIGHT Technique 8', sequence: ['special', 'light', 'heavy', 'dodge'], maximumGap: 595, score: 166, damageMultiplier: 1.52, resourceReward: 10, tags: ['knight', 'length-4'] },
    { id: 'knight-combo-9', name: 'KNIGHT Technique 9', sequence: ['light', 'heavy', 'dodge', 'special', 'light'], maximumGap: 620, score: 184, damageMultiplier: 1.58, resourceReward: 11, tags: ['knight', 'length-5'] },
    { id: 'knight-combo-10', name: 'KNIGHT Technique 10', sequence: ['heavy', 'dodge', 'special', 'light', 'heavy', 'dodge'], maximumGap: 645, score: 202, damageMultiplier: 1.64, resourceReward: 12, tags: ['knight', 'length-6'] },
    { id: 'knight-combo-11', name: 'KNIGHT Technique 11', sequence: ['dodge', 'special'], maximumGap: 670, score: 220, damageMultiplier: 1.70, resourceReward: 13, tags: ['knight', 'length-2'] },
    { id: 'knight-combo-12', name: 'KNIGHT Technique 12', sequence: ['special', 'light', 'heavy'], maximumGap: 695, score: 238, damageMultiplier: 1.76, resourceReward: 14, tags: ['knight', 'length-3'] },
    { id: 'mage-combo-1', name: 'MAGE Technique 1', sequence: ['ranged', 'light'], maximumGap: 420, score: 40, damageMultiplier: 1.10, resourceReward: 3, tags: ['mage', 'length-2'] },
    { id: 'mage-combo-2', name: 'MAGE Technique 2', sequence: ['light', 'hold', 'special'], maximumGap: 445, score: 58, damageMultiplier: 1.16, resourceReward: 4, tags: ['mage', 'length-3'] },
    { id: 'mage-combo-3', name: 'MAGE Technique 3', sequence: ['hold', 'special', 'ranged', 'light'], maximumGap: 470, score: 76, damageMultiplier: 1.22, resourceReward: 5, tags: ['mage', 'length-4'] },
    { id: 'mage-combo-4', name: 'MAGE Technique 4', sequence: ['special', 'ranged', 'light', 'hold', 'special'], maximumGap: 495, score: 94, damageMultiplier: 1.28, resourceReward: 6, tags: ['mage', 'length-5'] },
    { id: 'mage-combo-5', name: 'MAGE Technique 5', sequence: ['ranged', 'light', 'hold', 'special', 'ranged', 'light'], maximumGap: 520, score: 112, damageMultiplier: 1.34, resourceReward: 7, tags: ['mage', 'length-6'] },
    { id: 'mage-combo-6', name: 'MAGE Technique 6', sequence: ['light', 'hold'], maximumGap: 545, score: 130, damageMultiplier: 1.40, resourceReward: 8, tags: ['mage', 'length-2'] },
    { id: 'mage-combo-7', name: 'MAGE Technique 7', sequence: ['hold', 'special', 'ranged'], maximumGap: 570, score: 148, damageMultiplier: 1.46, resourceReward: 9, tags: ['mage', 'length-3'] },
    { id: 'mage-combo-8', name: 'MAGE Technique 8', sequence: ['special', 'ranged', 'light', 'hold'], maximumGap: 595, score: 166, damageMultiplier: 1.52, resourceReward: 10, tags: ['mage', 'length-4'] },
    { id: 'mage-combo-9', name: 'MAGE Technique 9', sequence: ['ranged', 'light', 'hold', 'special', 'ranged'], maximumGap: 620, score: 184, damageMultiplier: 1.58, resourceReward: 11, tags: ['mage', 'length-5'] },
    { id: 'mage-combo-10', name: 'MAGE Technique 10', sequence: ['light', 'hold', 'special', 'ranged', 'light', 'hold'], maximumGap: 645, score: 202, damageMultiplier: 1.64, resourceReward: 12, tags: ['mage', 'length-6'] },
    { id: 'mage-combo-11', name: 'MAGE Technique 11', sequence: ['hold', 'special'], maximumGap: 670, score: 220, damageMultiplier: 1.70, resourceReward: 13, tags: ['mage', 'length-2'] },
    { id: 'mage-combo-12', name: 'MAGE Technique 12', sequence: ['special', 'ranged', 'light'], maximumGap: 695, score: 238, damageMultiplier: 1.76, resourceReward: 14, tags: ['mage', 'length-3'] },
    { id: 'ranger-combo-1', name: 'RANGER Technique 1', sequence: ['ranged', 'hold'], maximumGap: 420, score: 40, damageMultiplier: 1.10, resourceReward: 3, tags: ['ranger', 'length-2'] },
    { id: 'ranger-combo-2', name: 'RANGER Technique 2', sequence: ['hold', 'dodge', 'special'], maximumGap: 445, score: 58, damageMultiplier: 1.16, resourceReward: 4, tags: ['ranger', 'length-3'] },
    { id: 'ranger-combo-3', name: 'RANGER Technique 3', sequence: ['dodge', 'special', 'ranged', 'hold'], maximumGap: 470, score: 76, damageMultiplier: 1.22, resourceReward: 5, tags: ['ranger', 'length-4'] },
    { id: 'ranger-combo-4', name: 'RANGER Technique 4', sequence: ['special', 'ranged', 'hold', 'dodge', 'special'], maximumGap: 495, score: 94, damageMultiplier: 1.28, resourceReward: 6, tags: ['ranger', 'length-5'] },
    { id: 'ranger-combo-5', name: 'RANGER Technique 5', sequence: ['ranged', 'hold', 'dodge', 'special', 'ranged', 'hold'], maximumGap: 520, score: 112, damageMultiplier: 1.34, resourceReward: 7, tags: ['ranger', 'length-6'] },
    { id: 'ranger-combo-6', name: 'RANGER Technique 6', sequence: ['hold', 'dodge'], maximumGap: 545, score: 130, damageMultiplier: 1.40, resourceReward: 8, tags: ['ranger', 'length-2'] },
    { id: 'ranger-combo-7', name: 'RANGER Technique 7', sequence: ['dodge', 'special', 'ranged'], maximumGap: 570, score: 148, damageMultiplier: 1.46, resourceReward: 9, tags: ['ranger', 'length-3'] },
    { id: 'ranger-combo-8', name: 'RANGER Technique 8', sequence: ['special', 'ranged', 'hold', 'dodge'], maximumGap: 595, score: 166, damageMultiplier: 1.52, resourceReward: 10, tags: ['ranger', 'length-4'] },
    { id: 'ranger-combo-9', name: 'RANGER Technique 9', sequence: ['ranged', 'hold', 'dodge', 'special', 'ranged'], maximumGap: 620, score: 184, damageMultiplier: 1.58, resourceReward: 11, tags: ['ranger', 'length-5'] },
    { id: 'ranger-combo-10', name: 'RANGER Technique 10', sequence: ['hold', 'dodge', 'special', 'ranged', 'hold', 'dodge'], maximumGap: 645, score: 202, damageMultiplier: 1.64, resourceReward: 12, tags: ['ranger', 'length-6'] },
    { id: 'ranger-combo-11', name: 'RANGER Technique 11', sequence: ['dodge', 'special'], maximumGap: 670, score: 220, damageMultiplier: 1.70, resourceReward: 13, tags: ['ranger', 'length-2'] },
    { id: 'ranger-combo-12', name: 'RANGER Technique 12', sequence: ['special', 'ranged', 'hold'], maximumGap: 695, score: 238, damageMultiplier: 1.76, resourceReward: 14, tags: ['ranger', 'length-3'] },
    { id: 'rogue-combo-1', name: 'ROGUE Technique 1', sequence: ['light', 'dodge'], maximumGap: 420, score: 40, damageMultiplier: 1.10, resourceReward: 3, tags: ['rogue', 'length-2'] },
    { id: 'rogue-combo-2', name: 'ROGUE Technique 2', sequence: ['dodge', 'heavy', 'special'], maximumGap: 445, score: 58, damageMultiplier: 1.16, resourceReward: 4, tags: ['rogue', 'length-3'] },
    { id: 'rogue-combo-3', name: 'ROGUE Technique 3', sequence: ['heavy', 'special', 'light', 'dodge'], maximumGap: 470, score: 76, damageMultiplier: 1.22, resourceReward: 5, tags: ['rogue', 'length-4'] },
    { id: 'rogue-combo-4', name: 'ROGUE Technique 4', sequence: ['special', 'light', 'dodge', 'heavy', 'special'], maximumGap: 495, score: 94, damageMultiplier: 1.28, resourceReward: 6, tags: ['rogue', 'length-5'] },
    { id: 'rogue-combo-5', name: 'ROGUE Technique 5', sequence: ['light', 'dodge', 'heavy', 'special', 'light', 'dodge'], maximumGap: 520, score: 112, damageMultiplier: 1.34, resourceReward: 7, tags: ['rogue', 'length-6'] },
    { id: 'rogue-combo-6', name: 'ROGUE Technique 6', sequence: ['dodge', 'heavy'], maximumGap: 545, score: 130, damageMultiplier: 1.40, resourceReward: 8, tags: ['rogue', 'length-2'] },
    { id: 'rogue-combo-7', name: 'ROGUE Technique 7', sequence: ['heavy', 'special', 'light'], maximumGap: 570, score: 148, damageMultiplier: 1.46, resourceReward: 9, tags: ['rogue', 'length-3'] },
    { id: 'rogue-combo-8', name: 'ROGUE Technique 8', sequence: ['special', 'light', 'dodge', 'heavy'], maximumGap: 595, score: 166, damageMultiplier: 1.52, resourceReward: 10, tags: ['rogue', 'length-4'] },
    { id: 'rogue-combo-9', name: 'ROGUE Technique 9', sequence: ['light', 'dodge', 'heavy', 'special', 'light'], maximumGap: 620, score: 184, damageMultiplier: 1.58, resourceReward: 11, tags: ['rogue', 'length-5'] },
    { id: 'rogue-combo-10', name: 'ROGUE Technique 10', sequence: ['dodge', 'heavy', 'special', 'light', 'dodge', 'heavy'], maximumGap: 645, score: 202, damageMultiplier: 1.64, resourceReward: 12, tags: ['rogue', 'length-6'] },
    { id: 'rogue-combo-11', name: 'ROGUE Technique 11', sequence: ['heavy', 'special'], maximumGap: 670, score: 220, damageMultiplier: 1.70, resourceReward: 13, tags: ['rogue', 'length-2'] },
    { id: 'rogue-combo-12', name: 'ROGUE Technique 12', sequence: ['special', 'light', 'dodge'], maximumGap: 695, score: 238, damageMultiplier: 1.76, resourceReward: 14, tags: ['rogue', 'length-3'] },
  ];
}
